[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"
  functions = "client/functions"
  environment = { CI = "false" } 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
