[build]
   base = "/opt/build/repo/client"
  publish = "build"
  command = "npm run build"
  functionsDirectory = "/opt/build/repo/client/client/functions"
  environment = { CI = "false" } 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
